import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>C&M Eucalipto Tratado</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Site em Manutenção!
        </h1>

        <p className={styles.description}>
          Breve estaremmos com site disponível.
        </p>

        <div className={styles.grid}>
         

          <a href="https://www.google.com/maps/dir/-23.1046819,-46.7283876/C%26M+Eucalipto/@-23.1008025,-46.7309016,15z/data=!3m1!4b1!4m9!4m8!1m1!4e1!1m5!1m1!1s0x94cedb5a114b9f27:0xc7e8a1e8e15dc08f!2m2!1d-46.7178628!2d-23.0931194" className={styles.card}>
            <h2>Google Maps &rarr;</h2>
            <p>C&M Madeira Tratada e Celio Telas</p>
          </a>


          <a
            href="https://api.whatsapp.com/send/?phone=5511965712976&text&app_absent=0"
            className={styles.card}
          >
            <h2>WhatsApp &rarr;</h2>
            <p>
              Converse com +55 11 96571-2976.
            </p>
          </a>
          <a
            href="https://www.agetel.com.br/agetel~jarinu~eucaliptos--tratados-em-auto-clave~c---m--eucalipto-tratado~5038"
            className={styles.card}
          >
            <h2>Agetel &rarr;</h2>
            <p>Rod. Edgard Máximo Zambotto, Km 73
            José de Lima
Jarinu, SP
13.240-000.</p>
          </a>
          

          <a href="#" className={styles.card}>
            <h2>Serviços
              &rarr;</h2>
            <p>Eucaliptos tratados em auto-Clave,Barracões de Madeira,Cercas,Telhados</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
